name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install .
          python --version
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install pytkdocs[numpy-style]
          cd docsite
          mkdocs gh-deploy --force
